name: Mirror and run GitLab CI

on: 
  push:
    branches: 
      -  main
  workflow_dispatch: {} # manual dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Change to default branch
      run: git config --global init.defaultBranch main
    - uses: actions/checkout@v4
      with:
        fetch-depth: '1'
    - name: Mirror + trigger CICD
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://imigitlab.uni-muenster.de/${{ secrets.NAMESPACE }}/rlign.git"
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "imigitlab.uni-muenster.de"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
        GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }} 